### ISSUE TITLE
Is kGWASflow operational?

### ISSUE THREAD

**Issue by tomvanschaik** [akcorut/kGWASflow#1]
Dear Adnan Kivanc Corut,

I would like to experiment with the kmerGWAS workflow (Voichek, 2020), and while searching I stumbled upon your snakemake implementation. Obviously, this could be very helpful, in particular with the extensions that you implemented. 

It already seems very mature. However, I did notice that the supplied config file (`config/config.yaml`) is missing many paramaters (i.e. samtools), which prevents me from testing the pipeline. 

Can I ask you whether the workflow is already operational, even though it still is under development? And if so, whether you have an updated config file with the other parameters listed?

Thank you.

Best,
Tom

**Comment by akcorut** [comment]
Hi @tomvanschaik,

Thanks for your interest in the workflow. Looks like the original config file was missing the parameters from the latest commits. I have updated the config file and uploaded here. The updated config file should include all the parameters. Thanks for reporting this.

I'm still testing and debugging the pipeline but it should definitely be functional. Let me know if you test the pipeline and encounter any problems. It's still a beta version so it might have some minor problems. I'm currently working on it to release a stable version in upcoming weeks.

Thanks,
Kivanc

**Comment by akcorut** [comment]
A stable version of kGWASflow has been released. Release information can be found here: https://github.com/akcorut/kGWASflow/releases/tag/v1.0.0

I'm closing this issue but if you have any other questions/issues, please feel free to open a new one.

Thanks.
Kivanc
