### ISSUE TITLE
init step ?

### ISSUE THREAD

**Issue by ChristianDina** [akcorut/kGWASflow#13]
Hi all,
great tool thanks. I created/loaded the conda env, and this seem to work. At the init step, when I issue the command "kgwasflow init" (tried kGWASflow init as well), the command is not recognized.

Did anyone else encounter the same issus ?

**Comment by ChristianDina** [comment]
Hi, me again. This is solved. Actually, the python install was by default trying to install in the common dir of the cluster where I had no rights (error mesage was lost in some interm. files). We need to make sure we use the pythong version in our conda environment when we have a cluster.
Thanks

**Comment by akcorut** [comment]
Hi @ChristianDina,

Sorry for my late response. In order to understand what went wrong, would you mind giving me more details about how did you install kGWASflow, the full command you ran to initialize the pipeline, and the error message you got?

**Comment by ChristianDina** [comment]
Hi @akcorut , thanks for your reply. As I said, the command  python setup.py install.py install was using the python of the server in priority. I am looking back in my script.

**Comment by akcorut** [comment]
Hi @ChristianDina,

Thanks for the information. Did you install kGWASflow via Bioconda, as explained here: https://github.com/akcorut/kGWASflow#installing-via-bioconda, or here: https://github.com/akcorut/kGWASflow#installing-via-bioconda. If so, you shouldn't have to deal with setup.py or load any modules (except Anaconda, maybe).

**Comment by ChristianDina** [comment]
I see. actually for me, Bioconda did not work. However, because I am used to use github and conda install, I did not check any more on this path and just did the second option.

**Comment by akcorut** [comment]
@ChristianDina,

Should I close this issue? Please let me know if you are still having problems.

**Comment by ChristianDina** [comment]
Yes, sorry for overlookign this
