### ISSUE TITLE
RuleException:

### ISSUE THREAD

**Issue by DavideGue** [akcorut/kGWASflow#14]
After trying kgwas flow on an increasing number of samples (30,60 and 150 samples), in the last attempt to run it (on 150 sample) I got the following error:
RuleException:
CalledProcessError in file /home/davideg/miniconda3/envs/kgwasflow/lib/python3.11/site-packages/workflow/rules/count_kmers.smk, line 149:
Command 'source /home/davideg/miniconda3/envs/kgwasflow/bin/activate '/home/davideg/Desktop/kgwas_wd/.snakemake/conda/192ef8a8cd1a6b089d1e20bbdfeb303b_'; set -euo pipefail;  
        kmc -t6 -v -k31 -ci0 -b         @results/reads/WB-090/input_files.txt results/kmers_count/WB-090/output_kmc_all results/kmers_count/WB-090         1> results/kmers_count/WB-090/kmc_all.1 2> results/kmers_count/WB-090/kmc_all.2         > logs/count_kmers/kmc/WB-090/kmc_all.log' died with <Signals.SIGINT: 2>.
  File "/home/davideg/miniconda3/envs/kgwasflow/lib/python3.11/site-packages/workflow/rules/count_kmers.smk", line 149, in __rule_kmc_non_canonical
  File "/home/davideg/miniconda3/envs/kgwasflow/lib/python3.11/concurrent/futures/thread.py", line 58, in run

I'm running gwasflow on ubuntu 20.04:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           24
Model name:                      AMD Ryzen 5 3400G with Radeon Vega Graphics
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         1400.000
CPU max MHz:                     3700,0000
CPU min MHz:                     1400,0000
BogoMIPS:                        7386.10
Virtualization:                  AMD-V
L1d cache:                       128 KiB
L1i cache:                       256 KiB
L2 cache:                        2 MiB
L3 cache:                        4 MiB
NUMA node0 CPU(s):               0-7
Could it be a memory issue?

**Comment by DavideGue** [comment]
Hi @akcorut the log file you mention is an empty file. On the other hand I can move the analysis on a server available at our institution but it will requires some time. Therefore I will update you once I get access to the server.

**Comment by akcorut** [comment]
Hi @DavideGue,

Should I close this issue?

**Comment by DavideGue** [comment]
Hi @akcourt,
We experienced several crashes of our server and I did not try yet. But you can close it, eventually I will ask you to reopen it later, if possible!

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by akcorut** [comment]
Sure. Feel free to reopen the issue or create a new one if you are having other problems when using the workflow.

Thanks.
Kivanc
