### ISSUE TITLE
Temporary directory for downloading packages

### ISSUE THREAD

**Issue by nirwan1265** [akcorut/kGWASflow#22]
I am using an HPC server that does not allow me to download anything in the home directory. Is there a way I can change the directory for the downloads. This is the error i get:

> more stderr.2525 50 
> Traceback (most recent call last):
>   File "/usr/local/usrapps/maize/ntanduk/kgwasflow/lib/python3.11/site-packages/snakemake/__init__.py", line 584, in snakemake
>     workflow = Workflow(
>                ^^^^^^^^^
>   File "/usr/local/usrapps/maize/ntanduk/kgwasflow/lib/python3.11/site-packages/snakemake/workflow.py", line 242, in __init__
>     self.sourcecache = SourceCache()
>                        ^^^^^^^^^^^^^
>   File "/usr/local/usrapps/maize/ntanduk/kgwasflow/lib/python3.11/site-packages/snakemake/sourcecache.py", line 358, in __init__
>     self.runtime_cache = tempfile.TemporaryDirectory(dir=runtime_cache_parent)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/usrapps/maize/ntanduk/kgwasflow/lib/python3.11/tempfile.py", line 854, in __init__
>     self.name = mkdtemp(suffix, prefix, dir)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/usrapps/maize/ntanduk/kgwasflow/lib/python3.11/tempfile.py", line 368, in mkdtemp
>     _os.mkdir(file, 0o700)
> OSError: [Errno 122] Disk quota exceeded: '/home/ntanduk/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpui67fttu'
> ERROR:root:Error running Snakemake: Command '['snakemake', '--use-conda', '--conda-frontend', 'conda', '--cores', '16', '--snakefile', '/usr/local/usrapps/maize/ntanduk/
> kgwasflow/lib/python3.11/site-packages/workflow/Snakefile', '--configfile', '/usr/local/usrapps/maize/ntanduk/kgwasflow/lib/python3.11/site-packages/workflow/test/config
> _ecoli/config.yaml', '--dryrun', '--rerun-triggers', 'mtime', 'params', 'input', 'software-env', 'code']' returned non-zero exit status 1.

**Comment by akcorut** [comment]
Hi @nirwan1265, 

You can define a new working directory when you initialize and also when you run the pipeline with `--work-dir` option. For example:

```
# Initializing a new kgwasflow working dir
kgwasflow init --work-dir path/to/your/work_dir 

# Run kGWASflow with user defined working directory:
 kgwasflow run -t 16 --work-dir path/to/work_dir
```

For more information: https://github.com/akcorut/kGWASflow/wiki/Running-kGWASflow#running-kgwasflow-with-kgwasflow-run

**Comment by akcorut** [comment]
Closing this issue due to the lack of activity. Feel free to reopen if this issue persists.
