### ISSUE TITLE
spades step permission denied 

### ISSUE THREAD

**Issue by Kxpark** [akcorut/kGWASflow#4]
I have been having trouble with this step.

this shutil.Error occurs each time here. I tried manually setting each file permissions with chomd 755. I was hoping maybe you knew of an easier way to fix this. 

Thanks again for all the help!

![image](https://user-images.githubusercontent.com/104218928/216384080-36673e8d-942a-41b1-8060-4590bf6b8a94.png)

**Comment by akcorut** [comment]
Hey @Kxpark,

I haven't experienced this issue before but my research showed that this might be due to an input/output error on your end.

This issue on spades's GitHub repo seems very similar to your problem: https://github.com/ablab/spades/issues/1002

Best,
Kivanc

**Comment by Kxpark** [comment]
Howdy,

After trying to update packages and change my python to 3.11 to match the new spades of 3.15.5, I dropped the version of spades down to 3.15.4 and it is finally running.  Thank you again for the responses and the help.
